name: Check
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  check:
    timeout-minutes: 10
    runs-on: ubuntu-24.04-arm
    env:
      CARGO_INCREMENTAL: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: Check OpenTelemetry 0.30 feature
        run: cargo check --all-targets --features opentelemetry_0_30
      - name: Check OpenTelemetry 0.31 feature
        run: cargo check --all-targets --features opentelemetry_0_31
      - name: Check OpenTelemetry 0.32 feature
        run: cargo check --all-targets --features opentelemetry_0_32
      - name: Clippy
        run: cargo clippy --all --all-targets -- -D warnings
