name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  test:
    timeout-minutes: 20

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          key: v1 # increment this to bust the cache if needed
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
