name: Coverage
permissions: "write-all"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  tarpaulin:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2
      - name: Install cargo-tarpaulin
        run: cargo install cargo-tarpaulin
      - name: Run cargo-tarpaulin with SQLx
        run: |
          cargo tarpaulin --verbose --out Xml --skip-clean --workspace --timeout 300 -- --test-threads=1
          mv cobertura.xml cobertura-sqlx.xml
        env:
          DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb
      - name: Run cargo-tarpaulin with tokio-postgres
        run: |
          cargo tarpaulin --verbose --out Xml --skip-clean --workspace --no-default-features --features driver-tokio-postgres --timeout 300 -- --test-threads=1
          mv cobertura.xml cobertura-tokio-postgres.xml
        env:
          DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb
      - name: Run cargo-tarpaulin with combined drivers
        run: |
          cargo tarpaulin --verbose --out Xml --skip-clean --workspace --features driver-tokio-postgres --timeout 300 -- --test-threads=1
          mv cobertura.xml cobertura-combined.xml
        env:
          DATABASE_URL: postgres://testuser:testpassword@localhost:5432/testdb
      - name: Upload combined coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          file: ./cobertura-combined.xml
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload SQLx coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          file: ./cobertura-sqlx.xml
          flags: sqlx
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload tokio-postgres coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          file: ./cobertura-tokio-postgres.xml
          flags: tokio-postgres
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
